app:
    resource: '@AppBundle/Controller/'
    type: annotation

artgris_bundle_file_manager:
    resource: "@ArtgrisFileManagerBundle/Controller"
    type:     annotation
    prefix:   admin/manager


